name = "Farallon"
license = "MIT"
description = "minimalist"
homepage = "https://github.com/bigfa/hugo-theme-farallon"
tags = ["minimalist"]
features = ["minimalist"]
min_version = "0.146.0"

[author]
    name = "bigfa"
    homepage = "https://github.com/bigfa"